name: Frontend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 설치할 Node.js 버전을 지정합니다.

      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy build folder to EC2
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -r $GITHUB_WORKSPACE/build/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/git/front
            